site_name: Características de iKono Chat
site_url: https://iKonoChat.github.io
site_author: Alejandro Herrera
site_description: En esta página web encontrarás más información relacionada con el proyecto iKono Chat y una lista de todas sus características.

nav:
  - Características: index.md
  - Changelog: changelog.md

theme:
  favicon: assets/images/favicon.png
  font:
    text: montserrat
  name: material
  logo: assets/logo.png
  features:
    - toc.integrate
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: ikono
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"

      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css


